services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=edumento'
      - 'MONGO_INITDB_ROOT_PASSWORD=edumento'
      - 'MONGO_INITDB_ROOT_USERNAME=edumento'
    ports:
      - '27017:27017'
    volumes:
      - '~/edumento/mongodb:/data/db'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=edumento'
      - 'POSTGRES_PASSWORD=edumento'
      - 'POSTGRES_USER=edumento'
    ports:
      - '5432:5432'
    volumes:
      - '~/edumento/postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
