services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "~/edumento/mongodb1:/data/db"
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=edumento"
      - "POSTGRES_PASSWORD=edumento"
      - "POSTGRES_USER=edumento"
    ports:
      - "5432:5432"
    volumes:
      - "~/edumento/postgres_new_2:/var/lib/postgresql"
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
