# add default properites values for the spring boot application in yamel file
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edumneto
    username: edumento
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
