import { User } from './user.model';
import { Space } from './space.model';
import { Resource } from './resource.model';
import { Discussion } from './discussion.model';
import { Assessment } from './assessment.model';

export const MOCK_USER: User = {
    id: 1,
    login: 'user1',
    fullName: 'Test User',
    userType: 'USER',
    email: 'test@example.com',
    activated: true,
    lang: 'en',
    gender: 'MALE',
    mobile: '123456789',
    profession: 'Student',
    country: 'US',
    image: 'url/to/image',
    userStatus: 'Active',
    interests: 'Coding',
    birthDate: '2000-01-01',
    notification: true,
    emailNotification: false,
    autoJoin: false,
    spacesCount: 5,
    school: 'Tech University',
    permissions: { 'READ': true },
    spaceRolePermission: { 'OWNER': { 'DELETE': true } }
};

export const MOCK_SPACE: Space = {
    id: 101,
    name: 'Angular Course',
    description: 'Learn Angular',
    color: '#FF0000',
    image: 'url/to/image',
    thumbnail: 'url/to/thumb',
    isPrivate: false,
    rating: 4.5,
    newContent: true,
    newAssessment: false,
    newComments: false,
    favorite: true,
    owner: false,
    communitySize: 100,
    contentSize: 50,
    joinRequestsAllowed: true,
    autoWifiSyncAllowed: false,
    showCommunity: true,
    allowRecommendation: true,
    allowLeave: true,
    joinedStatus: 'JOINED',
    tags: ['education', 'tech'],
    creationDate: '2025-01-01T10:00:00Z',
    lastModified: '2025-01-02T10:00:00Z',
    lastAccessed: '2025-01-03T10:00:00Z',
    creator: { id: 1, name: 'Test User', thumbnail: 'thumb', role: 'OWNER' },
    community: [],
    role: 'VIEWER',
    permissions: { 'WRITE': 1 }
};

export const MOCK_RESOURCE: Resource = {
    id: 201,
    name: 'Intro Video',
    shelf: 'Module 1',
    checkSum: 'abc123hash',
    spaceId: 101,
    contentLength: 1024,
    ext: 'mp4',
    tags: ['intro', 'video'],
    type: 'VIDEO',
    thumbnail: 'url/to/thumb',
    contentUrl: 'url/to/video',
    allowUseOriginal: true,
    favorite: false,
    favoriteDate: '2025-01-01',
    fileName: 'intro.mp4',
    folderName: 'root',
    lastAccess: '2025-01-02T10:00:00Z',
    newContent: false,
    status: 'CONVERTED',
    newAnnotation: false,
    owner: true,
    numberOfViews: 10,
    numberOfAnnotation: 0,
    creator: { id: 1, name: 'Test User' },
    lastModifiedDate: '2025-01-01T10:00:00Z',
    creationDate: '2025-01-01T10:00:00Z'
};

export const MOCK_DISCUSSION: Discussion = {
    id: 'disc-001',
    title: 'Help with Component',
    body: 'How do I create a component?',
    resourceUrl: '',
    ownerThumb: 'thumb',
    ownerName: 'Test User',
    ownerId: 1,
    commentsCounter: 2,
    creationDate: '2025-01-03T10:00:00Z',
    contentId: 201,
    type: 'QUESTION',
    spaceId: 101
};

export const MOCK_ASSESSMENT: Assessment = {
    id: 301,
    title: 'Mid-term Exam',
    assessmentStatus: 'NOT_STARTED',
    creationDate: '2025-01-01T10:00:00Z',
    lastModifiedDate: '2025-01-01T10:00:00Z',
    publishedDate: '2025-01-05T10:00:00Z',
    userCounter: 0,
    corrected: 0,
    alreadyTaken: false,
    totalGrade: 0,
    totalPercentage: 0,
    topThree: false,
    bestAnswer: false,
    rank: 0,
    numberOfQuestions: 10,
    limitedByTime: true,
    owner: 1,
    isOwner: false,
    duration: 60,
    lockMint: true,
    randomizingQuestion: false,
    assessmentQuestionCreateModels: []
};
